---
branch: master
collapse_pre_releases: false
stop_at_branch_base: true
sections:
  - [aodh, aodh Chart]
  - [barbican, barbican Chart]
  - [ca-issuer, ca-issuer Chart]
  - [calico, calico Chart]
  - [ceilometer, ceilometer Chart]
  - [ceph-client, ceph-client Chart]
  - [ceph-mon, ceph-mon Chart]
  - [ceph-osd, ceph-osd Chart]
  - [ceph-provisioners, ceph-provisioners Chart]
  - [cinder, cinder Chart]
  - [daemonjob-controller, daemonjob-controller Chart]
  - [designate, designate Chart]
  - [elastic-apm-server, elastic-apm-server Chart]
  - [elastic-filebeat, elastic-filebeat Chart]
  - [elastic-metricbeat, elastic-metricbeat Chart]
  - [elastic-packetbeat, elastic-packetbeat Chart]
  - [elasticsearch, elasticsearch Chart]
  - [etcd, etcd Chart]
  - [falco, falco Chart]
  - [flannel, flannel Chart]
  - [fluentbit, fluentbit Chart]
  - [fluentd, fluentd Chart]
  - [glance, glance Chart]
  - [gnocchi, gnocchi Chart]
  - [grafana, grafana Chart]
  - [heat, heat Chart]
  - [helm-toolkit, helm-toolkit Chart]
  - [horizon, horizon Chart]
  - [ingress, ingress Chart]
  - [ironic, ironic Chart]
  - [keystone, keystone Chart]
  - [kibana, kibana Chart]
  - [kube-dns, kube-dns Chart]
  - [kubernetes-keystone-webhook, kubernetes-keystone-webhook Chart]
  - [kubernetes-node-problem-detector, kubernetes-node-problem-detector Chart]
  - [ldap, ldap Chart]
  - [libvirt, libvirt Chart]
  - [local-storage, local-storage Chart]
  - [lockdown, lockdown Chart]
  - [magnum, magnum Chart]
  - [mariadb, mariadb Chart]
  - [memcached, memcached Chart]
  - [metacontroller, metacontroller Chart]
  - [mistral, mistral Chart]
  - [mongodb, mongodb Chart]
  - [nagios, nagios Chart]
  - [namespace-config, namespace-config Chart]
  - [neutron, neutron Chart]
  - [nfs-provisioner, nfs-provisioner Chart]
  - [nova, nova Chart]
  - [octavia, octavia Chart]
  - [openvswitch, openvswitch Chart]
  - [ovn, ovn Chart]
  - [placement, placement Chart]
  - [postgresql, postgresql Chart]
  - [powerdns, powerdns Chart]
  - [prometheus-alertmanager, prometheus-alertmanager Chart]
  - [prometheus-blackbox-exporter, prometheus-blackbox-exporter Chart]
  - [prometheus-kube-state-metrics, prometheus-kube-state-metrics Chart]
  - [prometheus-node-exporter, prometheus-node-exporter Chart]
  - [prometheus-openstack-exporter, prometheus-openstack-exporter Chart]
  - [prometheus-process-exporter, prometheus-process-exporter Chart]
  - [prometheus, prometheus Chart]
  - [rabbitmq, rabbitmq Chart]
  - [rally, rally Chart]
  - [redis, redis Chart]
  - [registry, registry Chart]
  - [shaker, shaker Chart]
  - [tempest, tempest Chart]
  - [features, New Features]
  - [issues, Known Issues]
  - [upgrade, Upgrade Notes]
  - [api, API Changes]
  - [security, Security Issues]
  - [fixes, Bug Fixes]
template: |
  ---
  # To create a new release note related to a specific chart:
  # reno new <chart_name>
  #
  # To create a new release note for a common change (when multiple charts
  # are changed):
  # reno new common
  <chart_name>:
    - |
      Describe changes here, or remove this section. This paragraph will appear in
      the unnamed section of the <chart_name>/CHANGELOG.md for a given version.
  features:
    - |
      List new features here, or remove this section. If this section is given
      in the releasenotes/notes/<chart_name>-<sha>.yaml it will only appear in the
      "New Features" section of the <chart_name>/CHANGELOG.md. If this section is
      given in the releasenotes/notes/common-<sha>.yaml it will appear in the
      CHANGELOG.md files of all charts.
  issues:
    - |
      List known issues here, or remove this section. If this section is given
      in the releasenotes/notes/<chart_name>-<sha>.yaml it will only appear in the
      "Known Issues" section of the <chart_name>/CHANGELOG.md. If this section is
      given in the releasenotes/notes/common-<sha>.yaml it will appear in the
      CHANGELOG.md files of all charts.
  upgrade:
    - |
      List upgrade notes here, or remove this section. If this section is given
      in the releasenotes/notes/<chart_name>-<sha>.yaml it will only appear in the
      "Upgrade Notes" section of the <chart_name>/CHANGELOG.md. If this section is
      given in the releasenotes/notes/common-<sha>.yaml it will appear in the
      CHANGELOG.md files of all charts.
  api:
    - |
      List API changes here (e.g. values format), or remove this section. If this section is given
      in the releasenotes/notes/<chart_name>-<sha>.yaml it will only appear in the
      "API Changes" section of the <chart_name>/CHANGELOG.md. If this section is
      given in the releasenotes/notes/common-<sha>.yaml it will appear in the
      CHANGELOG.md files of all charts.
  security:
    - |
      List security issues here, or remove this section. If this section is given
      in the releasenotes/notes/<chart_name>-<sha>.yaml it will only appear in the
      "Security Issues" section of the <chart_name>/CHANGELOG.md. If this section is
      given in the releasenotes/notes/common-<sha>.yaml it will appear in the
      CHANGELOG.md files of all charts.
  fixes:
    - |
      List bug fixes here, or remove this section. If this section is given
      in the releasenotes/notes/<chart_name>-<sha>.yaml it will only appear in the
      "Bug Fixes" section of the <chart_name>/CHANGELOG.md. If this section is
      given in the releasenotes/notes/common-<sha>.yaml it will appear in the
      CHANGELOG.md files of all charts.
  ...
...
